name: Build and publish SDK package

on: [push, pull_request]

env:
  PUBLISH: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      PUBLISH: ${{ env.PUBLISH }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - uses: actions/cache@v3
        with:
          path: |
            .yarn
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - run: yarn set version $( grep -Po  'packageManager": "yarn@\K[^"]+' package.json )
      - run: yarn install --immutable
      # - run: yarn build
      # - run: yarn bundle
      # - run: yarn lint:nofix
      # - run: yarn format:check
      - run: yarn build:lib
      - name: Cache package
        if: env.PUBLISH == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist
            index.d.ts
            package.json
            README.md

  publish:
    name: Publish package
    needs: build
    if: needs.build.outputs.PUBLISH == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore dist
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Setup Node (using cache)
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Enable corepack
        run: corepack enable

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

